import streamlit as st
from typing import Dict, Any


def render_study_pack_view(pack: Dict[str, Any]):
    """
    Renders Tab 3: Visual study guide pack display:
    - Synthesized summary notes
    - Study roadmap timeline
    - Key terms glossary
    - 5 Short conceptual Q&As with collapsible model answers
    """
    if not pack:
        st.info("ℹ️ No study pack generated yet. Go to **Tab 2 (Configure & Generate)** to build your study pack!")
        return

    title = pack.get("title", "Study Guide Pack")
    difficulty = pack.get("difficulty", "Intermediate")

    st.markdown(f"# 📚 {title}")
    st.markdown(f"**Difficulty Level:** `{difficulty}` | **Generated by AI Study Assistant**")
    st.divider()

    # Section 1: Study Roadmap
    roadmap = pack.get("roadmap", [])
    if roadmap:
        st.markdown("### 🗺️ Suggested Study Roadmap")
        cols = st.columns(len(roadmap) if len(roadmap) <= 5 else 5)
        for idx, step in enumerate(roadmap[:5]):
            with cols[idx]:
                st.markdown(f"""
                <div style="background-color: #1e293b; padding: 14px; border-radius: 8px; border-left: 4px solid #38bdf8; border: 1px solid #334155; margin-bottom: 10px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.3);">
                    <div style="font-size: 11px; color: #38bdf8; font-weight: bold; letter-spacing: 0.5px;">STEP {step.get('step_number', idx+1)} ({step.get('estimated_minutes', 30)}m)</div>
                    <div style="font-weight: 600; color: #f8fafc; margin: 4px 0;">{step.get('topic', '')}</div>
                    <div style="font-size: 12px; color: #94a3b8;">{step.get('action_item', '')}</div>
                </div>
                """, unsafe_allow_html=True)
        st.write("")

    # Section 2: Summary Notes
    st.markdown("### 📖 High-Yield Summary Notes")
    summary = pack.get("summary_notes", "")
    st.markdown(summary)
    st.divider()

    # Section 3: Glossary
    glossary = pack.get("glossary", [])
    if glossary:
        st.markdown("### 🏷️ Key Terms & Concepts Glossary")
        search_query = st.text_input("🔍 Filter glossary terms...", key="glossary_search")

        filtered_glossary = [
            g for g in glossary
            if search_query.lower() in g.get("term", "").lower() or search_query.lower() in g.get("definition", "").lower()
        ] if search_query else glossary

        glossary_cols = st.columns(2)
        for idx, item in enumerate(filtered_glossary):
            with glossary_cols[idx % 2]:
                with st.expander(f"📌 **{item.get('term')}**", expanded=True):
                    st.write(item.get("definition"))

        st.divider()

    # Section 4: Short Q&As
    short_qas = pack.get("short_qas", [])
    if short_qas:
        st.markdown("### ❓ Short Analytical Questions & Model Solutions")
        st.caption("Test your recall by thinking of an answer before expanding the model solution.")

        for qa in short_qas:
            q_num = qa.get("id")
            q_text = qa.get("question")
            model_ans = qa.get("model_answer")
            key_pts = qa.get("key_points", [])

            with st.expander(f"**Question {q_num}: {q_text}**"):
                st.markdown(f"**Model Solution:**\n\n{model_ans}")
                if key_pts:
                    st.markdown("**Key Scoring Points:**")
                    for pt in key_pts:
                        st.markdown(f"- {pt}")
