import io
import re
import html
import logging
from typing import Dict, Any
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    HRFlowable,
    KeepTogether
)

logger = logging.getLogger("exports.pdf")


def _safe_xml(text: str) -> str:
    """Safely escapes text and normalizes unicode characters so ReportLab default fonts never crash on latin-1."""
    if not text:
        return ""
    s = str(text)
    # Replace common typography unicode chars with clean ASCII equivalents
    replacements = {
        "\u2014": " - ",   # em-dash
        "\u2013": "-",     # en-dash
        "\u2015": " - ",
        "\u2012": "-",
        "\u2212": "-",
        "\u2018": "'",     # left single quote
        "\u2019": "'",     # right single quote
        "\u201c": '"',     # left double quote
        "\u201d": '"',     # right double quote
        "\u2022": "*",     # bullet
        "\u2026": "...",   # ellipsis
        "\u00a0": " ",     # non-breaking space
        "\u200b": "",      # zero-width space
        "\u2010": "-",
        "\u2011": "-",
    }
    for k, v in replacements.items():
        s = s.replace(k, v)

    # Remove markdown header hashes
    s = re.sub(r"(?m)^#{1,6}\s*", "", s)

    # Encode with replace to ensure no unencodable characters remain
    s = s.encode("latin-1", "replace").decode("latin-1")

    # Escape HTML special chars
    escaped = html.escape(s)
    # Convert escaped bold & italic markdown if any
    escaped = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", escaped)
    escaped = re.sub(r"\*(.*?)\*", r"<i>\1</i>", escaped)
    return escaped


def generate_study_pack_pdf(pack_data: Dict[str, Any]) -> io.BytesIO:
    """
    Builds a professional multi-page Study Pack PDF containing:
    - Styled Title & Metadata Header
    - Study Roadmap Sequence
    - Two-Column Key Terms Glossary
    - High-Yield Summary Notes
    - 5 Short Conceptual Q&As with Model Answers
    - 20 Multiple Choice Questions with Explanations & Answer Key
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=40,
        rightMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    # Custom styles
    primary_color = colors.HexColor("#1e293b")  # Dark slate
    accent_color = colors.HexColor("#2563eb")   # Royal blue
    text_color = colors.HexColor("#334155")     # Slate gray
    bg_subtle = colors.HexColor("#f8fafc")

    title_style = ParagraphStyle(
        "CoverTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=primary_color,
        spaceAfter=6
    )

    subtitle_style = ParagraphStyle(
        "CoverSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=11,
        leading=15,
        textColor=accent_color,
        spaceAfter=15
    )

    section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=17,
        textColor=primary_color,
        spaceBefore=14,
        spaceAfter=8
    )

    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13.5,
        textColor=text_color,
        spaceAfter=6
    )

    bold_body = ParagraphStyle(
        "BoldBody",
        parent=body_style,
        fontName="Helvetica-Bold",
        textColor=primary_color
    )

    term_style = ParagraphStyle(
        "GlossaryTerm",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9.5,
        leading=12,
        textColor=accent_color
    )

    def_style = ParagraphStyle(
        "GlossaryDef",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=text_color
    )

    story = []

    # Title & Metadata Banner
    raw_title = pack_data.get("title", "Study Guide and Exam Prep Pack")
    raw_difficulty = pack_data.get("difficulty", "Intermediate")
    title = _safe_xml(raw_title)
    difficulty = _safe_xml(raw_difficulty)
    story.append(Paragraph(title, title_style))
    story.append(Paragraph(f"Difficulty Level: <b>{difficulty}</b> | Generated by Study Guide AI Engine", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=accent_color, spaceBefore=0, spaceAfter=14))

    # SECTION 1: Suggested Study Roadmap
    roadmap = pack_data.get("roadmap", [])
    if roadmap:
        story.append(Paragraph("1. Suggested Study Roadmap", section_heading))
        roadmap_data = [[
            Paragraph("<b>Step</b>", bold_body),
            Paragraph("<b>Focus Topic</b>", bold_body),
            Paragraph("<b>Est. Time</b>", bold_body),
            Paragraph("<b>Action Item</b>", bold_body)
        ]]
        for step in roadmap:
            roadmap_data.append([
                Paragraph(_safe_xml(f"#{step.get('step_number', '')}"), body_style),
                Paragraph(_safe_xml(str(step.get("topic", ""))), bold_body),
                Paragraph(_safe_xml(f"{step.get('estimated_minutes', 30)} min"), body_style),
                Paragraph(_safe_xml(str(step.get("action_item", ""))), body_style)
            ])

        roadmap_table = Table(roadmap_data, colWidths=[0.6*inch, 1.8*inch, 0.9*inch, 4.0*inch])
        roadmap_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), bg_subtle),
            ('TEXTCOLOR', (0, 0), (-1, 0), primary_color),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(roadmap_table)
        story.append(Spacer(1, 14))

    # SECTION 2: Two-Column Key Terms Glossary
    glossary = pack_data.get("glossary", [])
    if glossary:
        story.append(Paragraph("2. Key Terms and Concepts Glossary", section_heading))
        glossary_rows = [[
            Paragraph("<b>Academic Term / Concept</b>", bold_body),
            Paragraph("<b>Precise Operational Definition</b>", bold_body)
        ]]
        for g in glossary:
            glossary_rows.append([
                Paragraph(_safe_xml(str(g.get("term", ""))), term_style),
                Paragraph(_safe_xml(str(g.get("definition", ""))), def_style)
            ])

        glossary_table = Table(glossary_rows, colWidths=[2.2*inch, 5.1*inch])
        glossary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), bg_subtle),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        story.append(glossary_table)
        story.append(Spacer(1, 14))

    # SECTION 3: Summary Notes
    summary_notes = pack_data.get("summary_notes", "")
    if summary_notes:
        story.append(Paragraph("3. Synthesized Summary Notes", section_heading))
        for line in summary_notes.split("\n"):
            line = line.strip()
            if not line:
                story.append(Spacer(1, 4))
            elif line.startswith("# "):
                story.append(Paragraph(_safe_xml(line.replace("# ", "")), section_heading))
            elif line.startswith("## "):
                story.append(Paragraph(_safe_xml(line.replace("## ", "")), bold_body))
            elif line.startswith("### "):
                story.append(Paragraph(_safe_xml(line.replace("### ", "")), bold_body))
            else:
                story.append(Paragraph(_safe_xml(line), body_style))
        story.append(Spacer(1, 14))

    # SECTION 4: 5 Short Q&As
    short_qas = pack_data.get("short_qas", [])
    if short_qas:
        story.append(PageBreak())
        story.append(Paragraph("4. Short Analytical Questions & Model Solutions", section_heading))
        story.append(Paragraph("Test your conceptual recall before reviewing model answers.", subtitle_style))

        for qa in short_qas:
            q_num = qa.get("id", "")
            q_text = _safe_xml(qa.get("question", ""))
            ans = _safe_xml(qa.get("model_answer", ""))
            kp = [_safe_xml(p) for p in qa.get("key_points", [])]

            kp_text = " | ".join(kp) if kp else ""
            qa_elements = [
                Paragraph(f"<b>Q{q_num}: {q_text}</b>", bold_body),
                Spacer(1, 3),
                Paragraph(f"<b>Model Answer:</b> {ans}", body_style),
            ]
            if kp_text:
                qa_elements.append(Paragraph(f"<i>Essential Key Points:</i> {kp_text}", body_style))
            qa_elements.append(Spacer(1, 8))
            story.append(KeepTogether(qa_elements))

    # SECTION 5: 20 Multiple Choice Questions
    mcqs = pack_data.get("mcqs", [])
    if mcqs:
        story.append(PageBreak())
        story.append(Paragraph("5. Practice Exam: 20 Multiple Choice Questions", section_heading))
        story.append(Paragraph("Select the single best answer for each question.", subtitle_style))

        for mcq in mcqs:
            m_id = mcq.get("id", "")
            m_q = _safe_xml(mcq.get("question", ""))
            options = mcq.get("options", [])
            corr = _safe_xml(mcq.get("correct_answer", ""))
            exp = _safe_xml(mcq.get("explanation", ""))

            mcq_flow = [
                Paragraph(f"<b>{m_q}</b>", bold_body),
                Spacer(1, 3)
            ]
            for opt in options:
                opt_label = _safe_xml(opt.get("label", ""))
                opt_text = _safe_xml(opt.get("text", ""))
                mcq_flow.append(Paragraph(f"&nbsp;&nbsp;<b>{opt_label})</b> {opt_text}", body_style))

            mcq_flow.append(Spacer(1, 3))
            mcq_flow.append(Paragraph(f"<b>Correct Answer:</b> Option {corr}", term_style))
            mcq_flow.append(Paragraph(f"<b>Explanation:</b> {exp}", body_style))
            mcq_flow.append(Spacer(1, 10))

            story.append(KeepTogether(mcq_flow))

    # Build PDF document
    doc.build(story)
    buffer.seek(0)
    return buffer
